---
title: "Word_Prediction"
author: "Abinashi Prakash"
date: "19 July 2019"
output:
  ioslides_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Overview

As a Capstone project, we have developed the Shiny App which will Predict the next possible word based on the User input. This course will start with below high level steps.(Refer Overview.docx for more detail.Link is available in slide-5)  

. Download source data and consider twitter,Blogs and News data set available in english language.

. Analyze a large corpus of text documents to discover the structure in the data and how words are put together.

. Clean and tokenize the sample data 

. Build a predictive text product.

##Pre-requisite Tasks
* Download source dataset from https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip.  
* In our analysis we will be using dataset available in English which is having three files as,Twitter, Blog and News.  
* Due to large dataset , capture Random sample data(Sample Size 2000 for this project) .  
* Clean the Sample data (This involves removing special characters, punctuations, numbers, whitespace, stem-Document,Stopwords,Offensive words and changing the text to lower case.).  
* Performa NGRAM tokenization to capture Uni, Bi and Tri Gram data in csv file.  
* Save Tri-Gram,Bi-Gram and Uni-Gram dataset in csv format and place in GitHub Shared repository.  

##Algorithm to predict word
* If cleaned Input word/s having length greater than or equal to 2,the next predicted word would be value of most frequent 3rd column in Three_gram file if below condition is true,  
     . Last Input word should match with 2nd column of Three_gram file and Second Last word should match with 1st column of Three_gram file.  
* If condition in step:1 is false then it will be searched in Two_gram file and next predict word would be the most frequent 2nd column in Two_gram file if below condition is true,  
     . Last Input word should match with 1st column of Two_gram file.  
* If cleaned Input word/s having length equal to 1,the next predicted word would be value of most frequent 2nd column in Two_gram file if below condition is true,  
     . Input word should match with 1st column of Two_gram file.  

##User Guide and Reference Links
Once Shiny App for Word prediction will be launched using below link,user needs to follow the steps   
Step1:Provide the one or multiple words including english Stop words in Sidebar panel under "Enter word/s".  
Step2:Validate the Most Preferred Predicted Word and top 10 probable words in Main panel under "Probable Words" section.  
Step3:Keep adding predicted or probable words in your Input to check next predicted and probable words.    
Links:--   
APP is running at :https://abinashiprakash.shinyapps.io/Word_Predictor/  
Code is available at :https://github.com/abinashi-prakash/Capstone_Project  
Detail Overview is available at :https://github.com/abinashi-prakash/Capstone_Project/blob/master/Overview.docx







